global:
  hosts:
    # domain: <your-domain> # Replace with your domain name
    https: false
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
  helmInstall: false

  extraEnv:
    GITLAB_RELATIVE_URL_ROOT: /gitlab

  gitlaly:
    enabled: false

  minio:
    enabled: false

  kas:
    enabled: false

certmanager-issuer:
  email: vikas@admin.com

gitlab:
  ingress:
    path: /gitlab(/|$)(.*)

gitaly:
  persistence:
    size: 2Gi

minio:
  persistence:
    size: 1Gi

registry:
  persistence:
    size: 2Gi

upgradeCheck:
  enabled: false

certmanager:
  installCRDs: false
  install: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

redis:
  install: false

postgresql:
  install: false